name: 'github2gcs'
description: 'Github repo backup to GCS bucket'   
inputs:
  workload_identity_provider: 
     description: "Workload Identity provider path"
     required: true
  service_account: 
      description: "GCS Service Account"
      required: true
  SLACK_WEBHOOK: 
     description: "Incoming Slack Webhook url"
     required: true
  GCS_BUCKET: 
     description: "GCS Bucket name"
     required: true
  myrepo: 
     description: "GitHub Repository name"
     required: true
  repodst:
     description: "Destenation folder in GCS Bucket"
     required: true
 # message_title:
#      description: "Slack message title"
#      required: true
#  message_body:
#      description: "Slack message body"
#      required: true
  CHANNEL_ID:
      description: "Slack channel to post the message"
runs:
   using: "composite"
   steps:
    - id: 'checkout'
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.myrepo }}
        path: ${{inputs.repodst }}
        fetch-depth: '0'
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}
    - id: 'sync-repo'
      uses: 'google-github-actions/setup-gcloud@v0'
      # Sync files to bucket
      # echo "Syncing bucket $BUCKET ..."
    - run:  gsutil -m rsync -r -c -d ./${{ inputs.repodst }} gs://${{ inputs.GCS_BUCKET }}/${{ inputs.repodst }}
      shell: bash
   # - name: Slack Notification
   #   if: ${{ failure() }}
   #   uses: rtCamp/action-slack-notify@v2
  #    env:
  #      SLACK_CHANNEL: alerts-and-notifications
  #      SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
   #     SLACK_ICON: ':alert:'
   #     SLACK_MESSAGE: '${{ github.event.repository.name }} backup failed!'
   #     SLACK_TITLE: GitHub repo backup failed
  #      SLACK_WEBHOOK: ${{ inputs.SLACK_WEBHOOK }}
    - name: Send custom JSON data to Slack workflow
      id: slack
      if: ${{ failure() }}
      uses: slackapi/slack-github-action@v1.22.0
      with:
        channel-id: alerts-and-notifications
        # This data can be any valid JSON from a previous step in the GitHub Action
        payload: |
           {
             "key": "value",
              "foo": "bar"
            }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK }}
