name: 'github2gcs'
description: 'Github repo backup to GCS bucket and Slack alert on failure.'   
inputs:
  workload_identity_provider: 
     description: "Workload Identity Povider Path"
     required: true
  service_account: 
      description: "GCS Service Account Name"
      required: true
  SLACK_WEBHOOK: 
     description: "Incoming Slack Webhook URL"
     required: true
  GCS_BUCKET: 
     description: "GCS Bucket Name"
     required: true
  myrepo: 
     description: "GitHub Repository Name"
     required: true
  repodst:
     description: "Destenation Folder in GCS Bucket"
     required: true
  CHANNEL_ID:
      description: "Slack Channel to Post the Message"
      required: true
  token:
      description: "Github token"
      required: true
runs:
   using: "composite"
   steps:
    - id: 'checkout'
      uses: actions/checkout@v3
   #   with:
   #     repository: ${{ inputs.myrepo }}
   #     path: ${{inputs.repodst }}
   #     fetch-depth: 0  
   # - run: cd ${{ inputs.repodst }} && git pull --all
    - run: git clone --mirror https://${{ github.actor }}:${{ inputs.token }}@github.com/${{ inputs.myrepo }}.git
      shell: bash
    - run: cd ${{ inputs.repodst }}.git && REMOTE=$(git remote) &&  git remote set-url "${REMOTE}" https://github.com/${{ inputs.myrepo }} && cd ..
      shell: bash
    - run: mkdir ${{ inputs.repodst }} && mv ${{ inputs.repodst }}.git ${{ inputs.repodst }}/.git
      shell: bash
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}
    - id: 'sync-repo'
      uses: 'google-github-actions/setup-gcloud@v0'
      # Sync files to bucket 
    - run:  gsutil -m rsync -r -c -d ./${{ inputs.repodst }} gs://${{ inputs.GCS_BUCKET }}/${{ inputs.repodst }}
      shell: bash
    - name: Post to a Slack channel
      if: ${{ failure() }}
      uses: slackapi/slack-github-action@v1.22.0
      with:
        # Slack channel id, channel name, or user id to post message.
        # See also: https://api.slack.com/methods/chat.postMessage#channels
        channel-id: ${{ inputs.CHANNEL_ID }}
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": ":alert: GitHub backup failed",
            "blocks": [
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Event:*\n${{ github.event.repository.name }} backup failed!"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*User:*\n${{ github.actor }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Url:*\nhttps://github.com/${{ inputs.myrepo }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Workflow:*\n${{ github.workflow }}"
                  }
                ]
              }
            ]
          }
      env:
          SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
